[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/smart-exam-backend-0.1.0-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "backend"
rootDir = "./backend"
healthcheckPath = "/api/health"
healthcheckTimeout = 300

[[services]]
name = "frontend"
rootDir = "./frontend"
healthcheckPath = "/"
healthcheckTimeout = 300
